"""Markdown/JSON report writer for Milestone 3 diagnostics (ASCII-safe)."""

from __future__ import annotations

import json
from pathlib import Path

from kaggle_vllm.diagnostics.evaluator import (
    MilestoneArtifactEvaluator,
    MilestoneEvaluation,
    evaluation_to_jsonable,
)


def _fmt(x: float | None, digits: int = 2) -> str:
    if x is None:
        return "n/a"
    return f"{x:.{digits}f}"


def render_markdown(m1: MilestoneEvaluation, m2: MilestoneEvaluation) -> str:
    lines: list[str] = []
    lines.append("# Milestone 3 — Communication-Cost Diagnostics Report")
    lines.append("")
    lines.append("Generated by `kaggle_vllm.diagnostics`.")
    lines.append("")
    lines.append("## Scientific boundaries")
    lines.append("")
    lines.append(
        "1. **Measured** quantities come from M1/M2 JSON evidence (throughput, latency matrix)."
    )
    lines.append(
        "2. **Derived proxy** = positive excess service time per token divided by an "
        "*assumed* Megatron collective count. This is **not** isolated alpha (alpha) "
        "from a classical alpha-beta fit."
    )
    lines.append(
        "3. **Hypothetical alpha-beta** terms are optional assumptions and are disabled "
        "in the default report path."
    )
    lines.append(
        "4. Host topology observed PHB on dual T4; that does **not** by itself prove "
        "NCCL/PCIe is the sole cause of TP deltas (compute/schedule/graph/memory interact)."
    )
    lines.append("")

    lines.append("## 1. Milestone 1 (offline comparisons)")
    lines.append("")
    for n in m1.notes:
        lines.append(f"- {n}")
    lines.append("")
    lines.append(
        "| Comparison | TP1 tok/s | TP2/candidate tok/s | Delta % | "
        "Layers (assumed) | Collectives/tok (assumed) | "
        "Excess-time proxy us/collective | Regime |"
    )
    lines.append("|---|---:|---:|---:|---:|---:|---:|---|")
    for c in m1.cells:
        proxy = _fmt(c.observed_excess_us_per_collective_proxy)
        lines.append(
            f"| `{c.label}` | {_fmt(c.measured_tp1_tok_s, 1)} | {_fmt(c.measured_tp2_tok_s, 1)} | "
            f"{c.measured_delta_percent:+.1f} | {c.assumed_num_layers} | "
            f"{c.assumed_collectives_per_token} | {proxy} | {c.measured_regime} |"
        )
    lines.append("")
    lines.append("### M1 cell notes")
    lines.append("")
    for c in m1.cells:
        lines.append(f"- `{c.label}`: {c.summary}")
        if c.proxy_caveat:
            lines.append(f"  - Proxy caveat: {c.proxy_caveat}")
    lines.append("")

    lines.append("## 2. Milestone 2 (online concurrency matrix)")
    lines.append("")
    for n in m2.notes:
        lines.append(f"- {n}")
    lines.append("")
    lines.append(
        "| c | TP1 tok/s | TP2 tok/s | Delta % | Excess ms/tok (if TP2 slower) | "
        "Proxy us/collective | Regime |"
    )
    lines.append("|---:|---:|---:|---:|---:|---:|---|")
    for c in m2.cells:
        lines.append(
            f"| {c.concurrency} | {_fmt(c.measured_tp1_tok_s)} | {_fmt(c.measured_tp2_tok_s)} | "
            f"{c.measured_delta_percent:+.1f} | {_fmt(c.measured_excess_ms_per_tok)} | "
            f"{_fmt(c.observed_excess_us_per_collective_proxy)} | {c.measured_regime} |"
        )
    lines.append("")

    lines.append("## 3. Model vs observation (crossover)")
    lines.append("")
    if m2.crossover is None:
        lines.append("No crossover object (missing M2 matrix).")
    else:
        x = m2.crossover
        lines.append(
            f"- **Measured throughput crossover concurrency:** "
            f"{x.measured_throughput_crossover_concurrency}"
        )
        if x.measured_throughput_crossover_concurrency is not None:
            lines.append(
                f"- **Measured rates at crossover:** "
                f"{_fmt(x.measured_crossover_tp1_tok_s)} -> "
                f"{_fmt(x.measured_crossover_tp2_tok_s)} tok/s"
            )
        lines.append(
            f"- **Model-predicted crossover concurrency:** "
            f"{x.model_predicted_crossover_concurrency}"
        )
        lines.append(f"- **Prediction status:** `{x.prediction_status}`")
        lines.append(f"- **Reason:** {x.prediction_reason}")
    lines.append("")

    lines.append("## 4. Optional hypothetical path")
    lines.append("")
    lines.append(
        "Default report keeps `enable_hypothetical=false`. Enabling it still does **not** "
        "validate PCIe Gen3 x8 beta or NVLink alpha claims without new measurements."
    )
    lines.append("")

    lines.append("## 5. Limitations")
    lines.append("")
    lines.append(
        "- Eager vs graph proxy divergence on OPT-125M shows the proxy is execution-mode dependent."
    )
    lines.append(
        "- Serving concurrency must not be silently treated as decode batch for payload S."
    )
    lines.append(
        "- No result here overwrites M1/M2 causal boundaries or claims sole NCCL/PCIe causality."
    )
    lines.append("")
    return "\n".join(lines) + "\n"


def generate_reports(
    m1_dir: str | Path,
    m2_dir: str | Path,
    output_dir: str | Path,
    *,
    enable_hypothetical: bool = False,
) -> dict:
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    m1 = MilestoneArtifactEvaluator(
        m1_dir, enable_hypothetical=enable_hypothetical
    ).parse_m1_evidence()
    m2 = MilestoneArtifactEvaluator(
        m2_dir, enable_hypothetical=enable_hypothetical
    ).parse_m2_concurrency_matrix()

    md = render_markdown(m1, m2)
    # Guarantee no BEL/control chars from accidental escapes
    md = "".join(ch if (ord(ch) >= 32 or ch in "\n\t") else "?" for ch in md)

    md_path = output_path / "M3_DIAGNOSTICS_REPORT.md"
    json_path = output_path / "M3_DIAGNOSTICS_REPORT.json"
    md_path.write_text(md, encoding="utf-8")
    payload = {
        "m1": evaluation_to_jsonable(m1),
        "m2": evaluation_to_jsonable(m2),
        "enable_hypothetical": enable_hypothetical,
    }
    json_path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    return {"markdown": str(md_path), "json": str(json_path)}


def main(argv: list[str] | None = None) -> int:
    import argparse

    p = argparse.ArgumentParser(
        description="Milestone 3 communication-cost diagnostics reporter"
    )
    p.add_argument(
        "--m1-dir",
        default="artifacts/kaggle-2026-09-01-milestone-1",
    )
    p.add_argument(
        "--m2-dir",
        default="artifacts/kaggle-2026-09-02-milestone-2",
    )
    p.add_argument(
        "--output-dir",
        default="artifacts/kaggle-2026-09-03-milestone-3",
    )
    p.add_argument(
        "--enable-hypothetical",
        action="store_true",
        help="Attach labeled hypothetical alpha-beta numbers (still not calibrated transport fits).",
    )
    p.add_argument(
        "--format",
        choices=("md", "json", "both"),
        default="both",
    )
    args = p.parse_args(argv)
    paths = generate_reports(
        args.m1_dir,
        args.m2_dir,
        args.output_dir,
        enable_hypothetical=args.enable_hypothetical,
    )
    if args.format == "md":
        print(paths["markdown"])
    elif args.format == "json":
        print(paths["json"])
    else:
        print(paths["markdown"])
        print(paths["json"])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
